yjs/yjs

tests/y-array.tests.js, types/YArray.js
Looks like it was missing a switching to the next item after processing a Type item, so once iterator met a Type it stuck on it. If more tests or something else is required I will be happy to do that.
=> updating YArray's iterator to iterate Types correctly 

README.md
/bower_components -> ./bower_components
=> Correct typo in README example

src/types/YXmlText.js
The element attribute loop use the index of the nodes array. Updated to use the index of the attributes array. The problem is that by the first node the code will only apply the first attribute and for the second node only the second attribute. In the other yXml types are fine.
=> Fix attrs loop in yXmlText

src/types/YText.js, tests/y-text.tests.js
This avoids text nodes in nested structures returning undefined when toJSON is called by a parent.
=> basic Y.Text toJSON returns {unformatted:string}

README.md
Here's a first draft!
I reasoned that it's most valuable to just know that this method exists, but I'm not sure if there's anything extra you wanted to communicate.
Fixes #222
=> Document the  doc.toJSON method

README.md
cattaz.io, unfortunately, is still only available over http, but I've raised an issue in the repo to enable https on github pages, which the site appears to be using.
=> update http links, where possible, to https

src/types/YArray.js
This is a convenience method for creating a Y.Array from a JS array.
=> add Y.Array.from

src/types/YXmlFragment.js
When you use a tree walker and it doesn't match any nodes, it will crash. This prevents the crash since null was being check but not for the type before iterating the loop.
=> fix crash when the walker didn't match because n will be null

README.md, src/types/YMap.js, tests/y-map.tests.js
Remove all elements from a YMap 
Uses `delete` via `forEach` to create an event history (is this the correct approach?)
=> add `clear` to YMap

src/types/YXmlElement.js, src/types/YXmlFragment.js, tests/y-xml.tests.js
I was attempting to clone a `Y.XmlFragment` and I noticed that the clone function didn't seem to work / look right. I can't figure out why the `.toJSON` for the original doesn't `===` the clone, so I need some help completing this PR.
What I'm really attempting to do is append some Prosemirror nodes to an existing `Y.XmlFragment`. The best idea I came up with was to create another Y.Doc from  via `prosemirrorToYDoc` in `y-prosemirror` and then clone/append the newly created `Y.XmlFragment` into the existing `Y.XmlFragment`. I haven't quite figured out how to get it all working yet, so any suggestions would be appreciated!
=> Fix XmlElement.clone and XmlFragment.clone

README.md
Hi, I'm not sure if you accept adding a new binding which is in alpha.
It's not tied to an app, but it's a two-way binding to a proxy state.
=> Add valtio-yjs binding in README

README.md
Someone else bought the domain and redirects it to a crummy google results reskin with ads.
According to the [FujitsuLaboratories/cattaz repo](https://github.com/FujitsuLaboratories/cattaz), the website has been terminated.
=> Remove broken link to terminated cattaz website

src/utils/UndoManager.js
Just in case you like the idea ;) I guess listening to `stack-item-added` is sufficient to re-check for state of stacks for end users.
=> Add canUndo/canRedo to UndoManager. Fixes #365

src/types/YText.js, tests/y-text.tests.js
Calling cleanupFormattingGap should not make a copy of the
attributes because it needs to be able to update them.
Fixes #305 with the suggestion from @calibr.
=> Avoid copying attribute map when deleting

src/types/YText.js, tests/undo-redo.tests.js, tests/y-text.tests.js
Fixes #392
I was able to track it down to some redundant formatting that was left from the format function.
I expected that the text contains following contents after Change 2 (`text.format(16, 4, { bold: null })`) from the issue:
```js
ContentString { str: 'Attack ships ' }
ContentFormat { key: 'bold', value: true }
ContentString { str: 'on ' }
ContentFormat { key: 'bold', value: null }
ContentString { str: 'fire' }
ContentString { str: ' off the shoulder of Orion.' }
```
But instead got this contents:
```js
ContentString { str: 'Attack ships ' }
ContentFormat { key: 'bold', value: true }
ContentString { str: 'on ' }
ContentFormat { key: 'bold', value: null }
ContentString { str: 'fire' }
ContentFormat { key: 'bold', value: true } // redundant
ContentFormat { key: 'bold', value: null } …
```
=> cleanup redundant text attributes when delete attributes

src/structs/ContentType.js, src/types/AbstractType.js, src/types/YArray.js, src/types/YMap.js, src/types/YText.js, src/types/YXmlEvent.js, src/utils/Doc.js, src/utils/Transaction.js, src/utils/YEvent.js
This PR makes the TypeScript type for `YEvent` subclasses include the accurate type for the `target` property (e.g. `YArray` for `YArrayEvent`, `YText` for `YTextEvent` etc.).
I found this useful for working with `observeDeep` in TypeScript because now I don't need as many casts or `instanceof` tests (e.g. it's enough to verify that `event` is `YMapEvent` without having to assert the type of `event.target` separately).
=> Add more accurate typing for YEvent.target

README.md
This PR adds [immer-yjs](https://github.com/sep2/immer-yjs) to Bindings section in readme.md.
`immer-yjs` allows manipulating `y.js` data types with the api provided by `immer`.
* Two-way binding between y.js and plain (nested) json object/array.
* Efficient snapshot update with structural sharing, same as `immer`.
* Updates to `y.js` are explicitly batched in transaction, you control the transaction boundary.
* Always opt-in, non-intrusive by nature (the snapshot is just a plain object after all).
* The snapshot shape & y.js binding aims to be fully customizable.
* Typescript all the way (pure js is also supported).
* Code is simple and small, no magic hidden behind, no vendor-locking.
=> add immer-yjs to Bindings

package-lock.json, package.json
After upgrading to the latest version (13.5.29), I started to see the
following error:
```
ERROR in ./node_modules/yjs/dist/yjs.mjs 4048:13-26
export 'isArray' (imported as 'array') was not found in 'lib0/array' (possible exports: appendTo, copy, create, equalFlat, every, flatten, from, last, some)
```
It looks like `array.isArray` was added to `lib0` in [v0.2.47](https://github.com/dmonad/lib0/releases/tag/v0.2.47).
Updating the version in `package.json` fixed the error in my project.
=> Upgrade lib0 from v0.2.43 to v0.2.47

package.json
I'm trying to yjs with TypeScript's experimental support for ECMAScript modules in node.js.
https://www.typescriptlang.org/docs/handbook/esm-node.html
To import the types correctly, we need to add `exports.types` field.
=> Add support for esm in node.js

src/index.js
Hi @dmonad
In Nimbus we are using `UpdateEncoderV1` but in new release of `yjs` its gone from exports. 
May we return it?
Thank you
=> export UpdateEncoderV1

src/index.js
[globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) is the JS standardised version of `global` (Node) and `window` (Browsers). 
This PR makes it so that we select `globalThis` if it's defined. Eventually, when the time comes, `window` and `global` can be removed.
I have no specific use case for this change. I suppose there's probably a JS runtime out that only defines `globalThis`. Just something I noticed as a small improvement while looking through the code.
=> Prefer globalThis over window and global

src/types/YMap.js
If the idea is to keep the API as close to the JS Map as possible, maybe we should consider not returning here.
Ref: https://github.com/microsoft/TypeScript/blob/v4.8.3/lib/lib.es2015.collection.d.ts#L28-L31
=> Remove unused return in `forEach` of `YMap`

README.md
Add my new [MongoDB Provider](https://github.com/MaxNoetzold/y-mongodb-provider) to the provider list in the README file so users can find it if they need one.
=> Add y-mongodb-provider to provider list in README

src/utils/UndoManager.js
UndoManager is currently only using the initial `captureTimeout` passed to the constructor. When moving this into `this.captureTimeout` we can now update the timeout after init. 
For example: we use `yUndoManager.captureTimeout = Number.MAX_VALUE` to temporarily pause stack item reporting for long user interactions.
=> Allow updating captureTimeout on UndoManager instances

src/utils/DeleteSet.js
This PR modifies the encoding of the delete set in `encodeStateAsUpdate` so that the entries are sorted in descending client ID order. 
This makes it possible to perform hash or checksum on the encoded state of a document and get a consistent result across different peers if the states are equivalent.
=> Make encodeStateAsUpdate deterministic

README.md
The 'getting started' doesn't work without importing and creating the first doc.
=> Add missing getting-started steps

README.md
I've been using yjs since 2017. Excellent library.
oorja.io is my side-project that refuses to die. It uses the yjs doc for participant collaboration and persistence in apps like codeshare, excalidraw within.
Cheers
=> add oorja.io to who is using yjs

README.md
Feel free to modify if need be!
=> Added Liveblocks Yjs to the list of providers

INTERNALS.md
Fixes a couple typos I noticed in the documentation on Yjs' internals.
=> Correct typos in INTERNALS.md

README.md
Multiple people I talked to didn't figure this out and therefor sticked to V1. I hope this should make it easier for others to upgrade.
=> add documentation on V2 events

src/index.js
I'm trying to implement some end-to-end encryption updates, like `encryptUpdate(update, private) -> update,` that allows the server to merge updates and decode updates...(just like `obfuscateUpdate`), but the difference is contents are encrypted by `privateKey.` So that it can be safely saved to the server, but the update is still valid so that the server can validate if the document schema is correct.
Then, I found that some internal classes are not exposed, so it will make things hard to extend the existing logic. I would appreciate it if some internal types could be exposed to the downstream so that we can make the ecosystem better.
=> feat: expose some types

src/utils/Doc.js
This PR fixes an issue when we use `doc.emit('sync', [false])`, at the moment, it'll emit `load` and change `isLoaded` to `true`.
In our case, we call `doc.emit('sync', [false])` when our socket connection is dropped; and sometimes it can happen before the first time we called `doc.emit('sync', [true])`.
The alternative to this PR is to change the logic of the `sync` event to not accept an argument and to behave like the `load` event where calling it always set the state to true.
The workaround at the moment is to make sure to wrap `doc.emit('sync', [false])`  with `if (doc.isSynced) { }`.
=> Only emit "load" when sync is set to true

src/types/YMap.js
Some of `Y.Map`'s methods are typed as returning `IterableIterator<any>`, but they could be stronger. This PR replaces the `any` with the appropriate type parameter as follows:
| method | new return type |
| --- | --- |
| `values()` |  `IterableIterator<MapType>` |
| `entries()` | `IterableIterator<[string, MapType]>` |
| `[Symbol.iterator]()` | `IterableIterator<[string, MapType]>` |
=> Fix typing of `Y.Map` iterators

README.md, src/utils/Doc.js, tests/y-xml.tests.js
All shared types have top-level getters except `YXmlElement`. 
This PR adds `getXmlElement` to the `Doc` class.
```js
const doc = new Y.Doc()
const yxmlel = ydoc.getXmlElement('prop-name')
```
Reference:
- https://discuss.yjs.dev/t/why-does-the-ydoc-getxmlelement-method-not-exist/2249
=> Add top-level getXmlElement

INTERNALS.md
The `markPosition()` and `findMarker()` functions in `src/types/AbstractType.js` both handle **search marker** with an upper bound `maxSearchMarker`, which is defined as `const maxSearchMarker = 80`. but according to **INTERNALS.md**, it says `Yjs stores a cache of the 10 most recently looked up insert positions in the document.` Are they same concept? 
Give a try to update the value in **INTERNALS.md** if they are.
=> update search marker count in INTERNALS.md

src/utils/Doc.js, src/utils/Transaction.js
The `Y` class was replaced with `Y.Doc` some time ago, but some code comments is still related to `Y` instance or its `define` method, So try to update the outdated comments.
=> remove outdated Y instance in comments

README.md
The commmit https://github.com/yjs/y-websocket/commit/c3d14cf07d8628431a7480213131ce58cad9adc9 renamed `server.js` to `server.cjs`; mirror that change here.
<sub><a href="https://huly.app/guest/yjs?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjNjYWMyODYzNGI1M2M3ZjEyMGMxNjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.6oFZjDnwO2ulc1DbxefZQIaYXLUOf1lzbQC5G0nh-lc">Huly&reg;: <b>YJS-818</b></a></sub>
=> Fix y-websocket `server.cjs` path

README.md
I needed a way to persist YJS documents in my React Native app and was already using OP-SQLite, so I built a persistence provider called [y-op-sqlite](https://github.com/malte-j/y-op-sqlite) to store updates in the SQLite database. 
I'm happy about every bit of feedback!
<sub><a href="https://huly.app/guest/yjs?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjMxMDBjZjAyYzdiMjYwNDYzMTA4MTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.uy9o28z4fZ-Olcy6VaTTT-gaT73n60ExFgLikw_h7Ac">Huly&reg;: <b>YJS-815</b></a></sub>
=> Add y-op-sqlite to Readme

README.md
Add my new [PostgreSQL Provider](https://github.com/MaxNoetzold/y-postgresql) to the provider list in the README file so users can find it if they need one.
<sub><a href="https://huly.app/guest/yjs?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjRjYTJiYzEwYjdiODJiMTQ1MjY1NjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.99lSJbaUutmD7-4OnNpQLRa23abstvwYCbQu2lbVpEo">Huly&reg;: <b>YJS-822</b></a></sub>
=> Add y-postgresql to provider list in README

src/index.js
Useful for comparing snapshots.
I tried reimplementing it in my own code but it depends on the `DeleteSet` class, which is also not exported.
<sub><a href="https://huly.app/guest/yjs?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjYxOWZmNjhmODE1YzM1ZjQ0ZDdhMDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.BchwzO54K5QG9nzZJxSnFiQQn2D2EuEU2cHH2Ou21LI">Huly&reg;: <b>YJS-824</b></a></sub>
=> Export mergeDeleteSets

README.md
Upstream has removed this package in their repo, https://github.com/toeverything/AFFiNE/pull/6728
=> docs: remove `@toeverything/y-indexeddb`

README.md
This pull request updates the README.md by adding [yjs-pspdfkit](https://github.com/hoangqwe159/yjs-pspdfkit) to the list of bindings.
=> Add PSPDFKit binding to README.md

src/types/YText.js
Fixed an issue that the yText.applyDelta() accepted only Ops[], but not Delta.
=> fix(yText): applyDelta should support both Delta and Ops[]

README.md
AWS SageMaker was mentioned twice.  Remove one of the mentions.
=> README: Remove a duplicate SageMaker mention

README.md
Inserted new 'utilities' subheading under overview with entries for [y-utility](https://github.com/yjs/y-utility) and [yjs-orderedtree](https://github.com/Tulip-Writer/yjs-orderedtree).
forum post: https://discuss.yjs.dev/t/introducing-the-yjs-orderedtree-library/3748
=> Added utilities category to README

README.md
Hyperlink to y-sweet debugger "https://docs.jamsocket.com/y-sweet/advanced/debugger" is outdated. (404 error)
The docs seems to have been moved to "https://y-sweet.cloud/advanced/debugger".
=> README: Update outdated y-sweet debugger hyperlink
