- README.md
Two lines below it states you switch to semver, still there was 1.0... ;)
> Changed to semver ;)

- src/types/YText.js
- tests/y-text.tests.js
https://github.com/y-js/yjs/issues/124
> process embeds in YText.toDelta

- README.v13.md
Reference:
https://github.com/y-js/yjs/blob/master/src/types/YArray.js#L186
https://github.com/y-js/yjs/blob/master/src/types/AbstractType.js#L239
> Updated documentation for Y.Array forEach

- README.md
fixes #171 As always, it's an honor to submit a PR! 🐒 There was also a missing dot in the Y.XmlFragment title.
> Fixing Y.Map's documentation of forEach

- src/types/YText.js
- tests/y-text.tests.js
Fix for https://github.com/yjs/yjs/issues/187
I feel like this whole area deserves a re-write. Lots of duplication now and it's not obvious what the flow is (`packStr` seems pretty smelly to me)
> :bug: fix for #187

- README.md
Open questions:
- is the place fine? I don't really like it but couldn't find a better one.
- is the example itself fine?
> Add example of combining providers to README.md

- src/types/YMap.js
- tests/y-map.tests.js
> Add optional iterable param to Y.Map(), matching Map()

- src/types/YMap.js
- tests/y-map.tests.js
Mimics the `Map.prototype.size` property
> Add 'size' getter to Y.Map

- src/utils/Doc.js
- tests/index.js
- tests/y-doc.tests.js
> Add toJSON to YDoc

- INTERNALS.md
I wrote up a document describing some of what @dmonad explained to me about how Yjs works. I might be wrong about some details, and missing bits but I don't want to let perfect be the enemy of the good. (Having an incomplete document is better than nothing).
Kevin - please correct / edit any parts of this that I got wrong or things I missed!
> Added draft of INTERNALS.js

- src/utils/YEvent.js
I've added the typing, hope this will be fine with you!
This fixes: https://github.com/yjs/yjs/issues/232
> Amend typing of YEvent.changes, fixes #232

- package-lock.json
- tests/y-text.tests.js
Hey, @dmonad!
Test for the issue:
https://github.com/yjs/yjs/issues/275
> Yjs Ytext is merging empty lines despite different attributes

- README.md
Adds slate-yjs to the bindings inside in the readme.
> Add slate-yjs to bindings

- README.md
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
> Fix broken link for All Done

- src/types/YMap.js
Apologies, missed this clean up in my previous PR #309.
> remove console.log added in #309

- src/types/YXmlElement.js
- tests/y-xml.tests.js
add `hasAttribute` to xmlElement
> implement hasAttribute

- README.md
Hi @dmonad.
The explanation on 'users inserting elements in sequence' seems not right. The outcome(`[{id: {client, clock: 0}, content: 'ab'}]`) seems not corresponding to the input(`array.insert(0, ['a']), array.insert(0, ['b']);`).
It should be inserting text I think. And the insertion sequence should be `0` and `1`.
> Update an algorithm example

- README.md
Not sure what the preferred way to share it would be, for now I added it to the Bindings :)
> Add SyncedStore to readme

- README.md
Hello! 
Thanks for working and maintaining the project. It's very nice and easy to use. I especially like the orthogonal nature of it. I was able to create this provider and reuse a lot of other code and it just worked!
I figured I'd share my provider implementation in the README as well :)
> Add a new provider, y-libp2p

- README.md
> Update README.md (matrix-crdt)

- README.md
SyncedStore now supports Svelte: https://syncedstore.org/docs/svelte
> Update README.md (syncedstore svelte)

- INTERNALS.md
- src/structs/ContentType.js
- src/structs/Item.js
Just some trivial typos found when reading through the source code 👀
> fix minor typos

- src/utils/updates.js
> fix decodeUpdateV2 bug

- README.md
We've sponsored via GitHub and OpenCollective for a while and have made a few contributions. We'd like to be added to the list of users if appropriate. Thanks.
> Add Living Spec to readme

- README.md
> add AFFiNE to sponsor list

- tests/y-array.tests.js
This PR adds a test for `Y.Array.from`
> Add test for Y.Array.from

- src/types/YText.js
- src/utils/Transaction.js
> Ytext cleanup 538 refactor

- src/types/YText.js
- src/utils/Transaction.js
Fixes #522 but is a scarier change
> scan the document once for all ytexts when cleaning up

- src/utils/Transaction.js
- tests/y-map.tests.js
> invalidate cached path when changing currentTarget of event

- src/utils/DeleteSet.js
`equalDeleteSets` didn't work properly, because the `return false` in the foreach only quits a "single foreach", not the entire function
> fix equalDeleteSets

- README.md
Adds [IllumiDesk](https://illumidesk.com) as a reference user for Yjs.
> Adds IllumiDesk as a reference to the using list

- src/utils/encoding.js
I'm going through the source code of yjs and find some unused logic. This might improve a little performance
> fix: remove unused if-statement check

- README.md
Repo here: https://github.com/btw-so/btw
> Adding www.btw.so to the platforms who use Yjs

- README.md
According to https://evernote.com/blog/future-proofing-evernotes-foundations/ they have moved to Yjs lately
> Add Evernote as a user of Yjs

- README.md
As the name says, a new binding for the list :)
> Update README.md with mobx-keystone binding

- README.md
Added Professional Support section, along with information about Synergy Codes company
> Updated readme.md with Professional Support section

- src/utils/UndoManager.js
- tests/undo-redo.tests.js
> Facilitate referencing UndoManager StackItem inside Type observers

- README.md
I wanted to create a really fast and simple writing app that worked offline and across devices. yjs is the key that made this possible. 
Thanks!
> Update Readme who-is-using (thinkdeli.com)

- README.md
<sub><a href="https://huly.app/guest/w-githubdmonad-yjs-660d5772-70f06a0a22-d28cf5?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjJhOTQyMzRhZWRjZDliMjg0NDMyNzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.BvnUhaF1dLsg-ATjlGLYMKvAAAozctNtgu2XGjx_WgU">Huly&reg;: <b>YJS-811</b></a></sub>
> Add Hocuspocus as a backend provider

- README.md
See https://github.com/yjs/yjs/actions/runs/8840339867/job/24275471389
<sub><a href="https://huly.app/guest/w-githubdmonad-yjs-660d5772-70f06a0a22-d28cf5?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjJiMzhjMDRhZWRjZDliMjg0NGFmY2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.86PWzQmObr1X0bv3qIkMigy16oEXwqeQYDN6gS_nQH4">Huly&reg;: <b>YJS-812</b></a></sub>
> fix: markdownlint readme error

- src/types/YArray.js
- src/types/YXmlFragment.js
- src/utils/Transaction.js
- src/utils/encoding.js
* Try to remove unused `this._transaction` in `YArrayEvent`.
* Make `slice()` function' doc more accurate.
* Correct some minor typos.
<sub><a href="https://huly.app/guest/w-githubdmonad-yjs-660d5772-70f06a0a22-d28cf5?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjI5Y2NlMjRhZWRjZDliMjg0Mzg3ZGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.5IvT-RHiWjeP9RR113zdRW1MbC839phmbE-NN4OQdmg">Huly&reg;: <b>YJS-810</b></a></sub>
> remove unused _transaction in YArrayEvent

- README.md
<sub><a href="https://huly.app/guest/w-githubdmonad-yjs-660d5772-70f06a0a22-d28cf5?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjBkNjNiNThjN2YzNTBiMTEyMTNlZTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZG1vbmFkLXlqcy02NjBkNTc3Mi03MGYwNmEwYTIyLWQyOGNmNSIsInByb2R1Y3RJZCI6IiJ9.lIvNPFIBwT9Fg34-Xfg-6YGvz40uoNmSjnM9o2uQetw">Huly&reg;: <b>YJS-428</b></a></sub>
> add screen.garden as user

- README.md
Since we've contributed to `yjs` and use it in our product, I've wondered if we can enlist ourselves in the list of yjs users?
Thank you all so much :blush:
> Add QDAcity to `README.md`

- README.md
Add <https://scienhub.com> to the user list.
> add ScienHub as a user.

- README.md
This pull request updates the README.md by adding SuperViz to the list of providers. For more information about our integration and how to get started, you can refer to the documentation: [SuperViz Yjs Quickstart](https://docs.superviz.com/collaboration/integrations/YJS/quickstart).
Feel free to review and provide any feedback!
> Added SuperViz Provider to the list of providers

- src/types/YText.js
> Revert "fix(yText): applyDelta should support both Delta and Ops[]"

- README.md
'btw' was mentioned twice; remove one mention.
> README: Remove duplicate btw mention

- README.md
Ref: https://x.com/kevin_jahns/status/1904252641124753641
> Update README.md to add https://github.com/kapv89/k_yrs_go to persistence providers

- funding.json
- tests/testHelper.js
I recently discovered Yjs while working on CRDT development, and I'm really impressed by this project. While exploring the codebase and documentation, I noticed a few small typos that I thought might be worth fixing. 😀
- Fixed "randon" → "random" in `tests/testHelper.js` 
- Fixed "successfull" → "successful" in `funding.json`
> Fix typos in documentation and code comments
